version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    volumes:
      - nginx-data:/var/log/nginx

networks:
  inception:

volumes:
  nginx-data: