services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www:ro
    depends_on:
      - wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    depends_on:
      - mariadb

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/daong/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/daong/data/wordpress
      o: bind
