services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress:ro
    depends_on:
      - wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb

networks:
  inception:

volumes:
  dbdata:
  wordpress: