version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress:ro
    depends_on:
      - wordpress

  mariadb:
    image: mariadb:latest
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb

networks:
  inception:

volumes:
  dbdata:
  wordpress: